### ISSUE TITLE
Osram Lightiify

### ISSUE THREAD

**Issue by TDWhbp** [python-wink/python-wink#27]
Noting this here as well this is an enhancement request.
the code below is a pull from my list all devices from the API.
yes I named my color changing bulb the bat signal

```
{
      "uuid": "238539e2-1ad6-44ba-bc53-33c684c36e1d",
      "desired_state": {
        "powered": false,
        "brightness": 1,
        "color_model": "hsb",
        "hue": 0.35,
        "saturation": 1,
        "color_temperature": 1901
      },
      "last_reading": {
        "connection": true,
        "connection_updated_at": 1458628651.862995,
        "powered": false,
        "powered_updated_at": 1458628651.862995,
        "brightness": 1,
        "brightness_updated_at": 1458628651.862995,
        "color_model": "hsb",
        "color_model_updated_at": 1458628651.862995,
        "hue": 0.35,
        "hue_updated_at": 1458628651.862995,
        "saturation": 1,
        "saturation_updated_at": 1458628651.862995,
        "color_temperature": 1901,
        "color_temperature_updated_at": 1458628651.862995,
        "firmware_version": "0.1b02 / 0.3b22",
        "firmware_version_updated_at": 1458628651.862995,
        "firmware_date_code": "20150929N****",
        "firmware_date_code_updated_at": 1458628651.862995,
        "desired_powered_updated_at": 1458628650.8619466,
        "desired_brightness_updated_at": 1458628820.0301423,
        "desired_color_model_updated_at": 1458628820.0301423,
        "desired_hue_updated_at": 1458628820.0301423,
        "desired_saturation_updated_at": 1458628820.0301423,
        "desired_color_temperature_updated_at": 1458628820.0301423,
        "powered_changed_at": 1458628650.8134031,
        "brightness_changed_at": 1458122238.7788615,
        "connection_changed_at": 1457517588.4372394,
        "desired_powered_changed_at": 1458628650.8619466,
        "desired_brightness_changed_at": 1458628381.8566465,
        "firmware_date_code_changed_at": 1457521561.0603704,
        "color_model_changed_at": 1457521797.6389458,
        "hue_changed_at": 1457595786.5472758,
        "saturation_changed_at": 1457595782.71269,
        "color_temperature_changed_at": 1457521786.911106,
        "firmware_version_changed_at": 1457521561.0603704,
        "desired_color_model_changed_at": 1458620834.569744,
        "desired_hue_changed_at": 1457595786.605935,
        "desired_saturation_changed_at": 1457595782.8273423,
        "desired_color_temperature_changed_at": 1457521921.4747667
      },
      "light_bulb_id": "1515274",
      "name": "Bat Signal",
      "locale": "en_us",
      "units": {},
      "created_at": 1457517586,
      "hidden_at": null,
      "capabilities": {
        "fields": [
          {
            "field": "connection",
            "type": "boolean",
            "mutability": "read-only"
          },
          {
            "field": "powered",
            "type": "boolean",
            "mutability": "read-write"
          },
          {
            "field": "brightness",
            "type": "percentage",
            "mutability": "read-write"
          },
          {
            "field": "color_model",
            "type": "string",
            "choices": [
              "rgb",
              "hsb",
              "color_temperature"
            ]
          },
          {
            "field": "hue",
            "type": "percentage",
            "mutability": "read-write"
          },
          {
            "field": "saturation",
            "type": "percentage",
            "mutability": "read-write"
          },
          {
            "field": "color_temperature",
            "range": [
              1900,
              6500
            ],
            "type": "integer",
            "mutability": "read-write"
          }
        ],
        "color_changeable": true
      },
      "triggers": [],
      "manufacturer_device_model": "sylvania_sylvania_rgbw",
      "manufacturer_device_id": null,
      "device_manufacturer": "sylvania",
      "model_name": "Lightify RGBW Bulb",
      "upc_id": "509",
      "upc_code": "4613573703",
      "gang_id": null,
      "hub_id": "381678",
      "local_id": "37",
      "radio_type": "zigbee",
      "linked_service_id": null,
      "lat_lng": [
        null,
        null
      ],
      "location": "",
      "order": 0
    },
```

**Comment by TDWhbp** [comment]
I just updated HA and found that my bat signal has color temp. Should i be able to change colors?

**Comment by bradsk88** [comment]
The goal of the last update was for you to be able to change color.
If you can't, I'll need to add support.

Thanks for the API response.  I'll look into this ASAP.

**Comment by bradsk88** [comment]
RGB was working for me when I released 0.7.4 but, upon upgrading HA tonight, I am seeing the missing RGB selector as well.

Will investigate soon.

**Comment by w1ll1am23** [comment]
@TDWhbp Can you see if this is working in the newest HomeAssistant release 0.27.0?

**Comment by cbulock** [comment]
I just tested this on 0.27.1 and I'm still not seeing the option to set colors for the Osram bulbs.  I did notice this error on startup which I believe is new

```
16-08-31 17:06:40 ERROR (ThreadPool Worker 0) [homeassistant.components.light] Error while setting up platform wink
Traceback (most recent call last):
File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 98, in _setup_platform
discovery_info)
File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/light/wink.py", line 39, in setup_platform
WinkLight(light) for light in pywink.get_bulbs())
File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 155, in add_entities
if self.component.add_entity(entity, self):
File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity_component.py", line 125, in add_entity
entity.update_ha_state()
File "/usr/local/lib/python3.4/dist-packages/homeassistant/helpers/entity.py", line 157, in update_ha_state
attr = self.state_attributes or {}
File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/light/__init__.py", line 292, in state_attributes
value = getattr(self, prop)
File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/light/wink.py", line 72, in color_temp
self.wink.color_temperature_kelvin())
File "/usr/local/lib/python3.4/dist-packages/homeassistant/util/color.py", line 229, in color_temperature_kelvin_to_mired
return 1000000 / kelvin_temperature
TypeError: unsupported operand type(s) for /: 'int' and 'NoneType'
```

**Comment by w1ll1am23** [comment]
@cbulock strange, HA/Python-Wink are detecting that the bulb supports temperature but for some reason it is like the 'color_temperature' field isn't in 'last_reading'. Can you verify your JSON looks like @TDWhbp and has 'color_temperature' listed in 'last_reading' and in 'choices'?

**Comment by cbulock** [comment]
This is what my JSON looks like and I'm seeing color_temperature mentioned in those various places:

```
    {
      "uuid": "e34d6c2a-6192-449b-b643-264859502a59",
      "desired_state": {
        "powered": false,
        "brightness": 1,
        "color_model": "hsb",
        "hue": 0.97,
        "saturation": 0.14,
        "color_temperature": null
      },
      "last_reading": {
        "connection": true,
        "connection_updated_at": 1472678563.8270564,
        "powered": false,
        "powered_updated_at": 1472678563.8270564,
        "brightness": 1,
        "brightness_updated_at": 1472678563.8270564,
        "color_model": "hsb",
        "color_model_updated_at": 1472678563.8270564,
        "hue": 0.97,
        "hue_updated_at": 1472678563.8270564,
        "saturation": 0.14,
        "saturation_updated_at": 1472678563.8270564,
        "color_temperature": null,
        "color_temperature_updated_at": null,
        "firmware_version": "0.1b02 / 0.3b32",
        "firmware_version_updated_at": 1472678563.8270564,
        "firmware_date_code": "20151210N****",
        "firmware_date_code_updated_at": 1472678563.8270564,
        "desired_powered_updated_at": 1472678562.872169,
        "desired_brightness_updated_at": 1472678699.0596335,
        "desired_color_model_updated_at": 1472678699.0596335,
        "desired_hue_updated_at": 1472678699.0596335,
        "desired_saturation_updated_at": 1472678699.0596335,
        "desired_color_temperature_updated_at": 1472678699.0596335,
        "powered_changed_at": 1472678562.7870557,
        "brightness_changed_at": 1472599736.4935267,
        "connection_changed_at": 1472599736.689738,
        "firmware_date_code_changed_at": 1472599793.0460696,
        "firmware_version_changed_at": 1472599737.478466,
        "color_model_changed_at": 1472599737.478466,
        "hue_changed_at": 1472599858.9426787,
        "saturation_changed_at": 1472599858.9426787,
        "desired_powered_changed_at": 1472678562.872169,
        "desired_color_model_changed_at": 1472599859.7020388,
        "desired_hue_changed_at": 1472599859.7020388,
        "desired_saturation_changed_at": 1472599859.7020388,
        "desired_brightness_changed_at": 1472676213.51692,
        "desired_color_temperature_changed_at": 1472600006.033472
      },
      "subscription": {
        "pubnub": {
          "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
          "channel": "e9f3f8022ba8465463f572a19f95d8601c1559fc|light_bulb-1964639|user-362284"
        }
      },
      "light_bulb_id": "1964639",
      "name": "Outdoor Light Front Porch",
      "locale": "en_us",
      "units": {},
      "created_at": 1472599736,
      "hidden_at": null,
      "capabilities": {
        "fields": [
          {
            "type": "boolean",
            "field": "connection",
            "mutability": "read-only"
          },
          {
            "type": "boolean",
            "field": "powered",
            "mutability": "read-write"
          },
          {
            "type": "percentage",
            "field": "brightness",
            "mutability": "read-write"
          },
          {
            "type": "string",
            "field": "color_model",
            "choices": [
              "rgb",
              "hsb",
              "color_temperature"
            ]
          },
          {
            "type": "percentage",
            "field": "hue",
            "mutability": "read-write"
          },
          {
            "type": "percentage",
            "field": "saturation",
            "mutability": "read-write"
          },
          {
            "type": "integer",
            "field": "color_temperature",
            "range": [
              2000,
              6500
            ],
            "mutability": "read-write"
          }
        ],
        "color_changeable": true
      },
      "triggers": [],
      "manufacturer_device_model": "sylvania_sylvania_rgbw",
      "manufacturer_device_id": null,
      "device_manufacturer": "sylvania",
      "model_name": "Lightify RGBW Bulb",
      "upc_id": "593",
      "upc_code": "046135737039",
      "gang_id": null,
      "hub_id": "284481",
      "local_id": "45",
      "radio_type": "zigbee",
      "linked_service_id": null,
      "lat_lng": [
        null,
        null
      ],
      "location": "",
      "order": 0
    },
```

**Comment by w1ll1am23** [comment]
Ahhh, bingo. The problem is the value for color_temperature is null. Not sure why it would be set that way. Can you adjust the bulb temperature in the Wink App? If so try changing it to something and re-run the API call. It sounds like Null is a valid response from Wink so we are going to need to code around that, but changing it to something in the Wink app, and restarting HA will be a good test to see if that is the only thing wrong.

**Comment by cbulock** [comment]
That error I encountered may have been a one-off thing.  I've been trying to recreate it by having the lights turned off, set to a white temp, set to a color, it's not showing up any further. 

However, in none of those situations am I seeing the ability to select a color for the lights in the UI.

**Comment by w1ll1am23** [comment]
I think you might only get that error once during startup, have you tried
restarting HA? I would expect, although I could be wrong, once this is
working you would have a temperature slider as well as a color picker.

**Comment by cbulock** [comment]
Yea, I've been restarting HA between each change I've made

**Comment by w1ll1am23** [comment]
Thanks for the info, I'll try to take another look at the code tomorrow and
see if anything stands out.

**Comment by cbulock** [comment]
In case it's helpful, the previous output was from a light that was off.  I'm including a couple others.

Light on, but in white temp mode

```
{
  "uuid": "2d92b586-e80e-42d1-baa8-0ca5f99aa0f4",
  "desired_state": {
    "powered": false,
    "brightness": 0.75,
    "color_model": "color_temperature",
    "hue": 0,
    "saturation": 0,
    "color_temperature": 5000
  },
  "last_reading": {
    "connection": false,
    "connection_updated_at": 1472672905.2170146,
    "powered": false,
    "powered_updated_at": 1472036093.2467554,
    "brightness": 0.75,
    "brightness_updated_at": 1471997932.7267272,
    "color_model": "color_temperature",
    "color_model_updated_at": 1467693008.822817,
    "hue": 0,
    "hue_updated_at": 1471281999.3478863,
    "saturation": 0,
    "saturation_updated_at": 1471281999.392321,
    "color_temperature": 5000,
    "color_temperature_updated_at": 1471997932.7267272,
    "firmware_version": "0.1b02 / 0.3b32",
    "firmware_version_updated_at": 1471396549.5847716,
    "firmware_date_code": "20150929N****",
    "firmware_date_code_updated_at": 1460062630.7030988,
    "desired_powered_updated_at": 1472555082.073781,
    "desired_brightness_updated_at": 1472555082.073781,
    "desired_color_model_updated_at": 1472531557.041851,
    "desired_hue_updated_at": 1472262159.1688757,
    "desired_saturation_updated_at": 1472262159.1688757,
    "desired_color_temperature_updated_at": 1472445151.368655
  },
  "subscription": {
    "pubnub": {
      "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
      "channel": "2ed75fb06374962cb32a11dd45cd63f0b4253dbe|light_bulb-1597910|user-362284"
    }
  },
  "light_bulb_id": "1597910",
  "name": "Outdoor Light Garage Right",
  "locale": "en_us",
  "units": {},
  "created_at": 1460062626,
  "hidden_at": null,
  "capabilities": {
    "fields": [
      {
        "type": "boolean",
        "field": "connection",
        "mutability": "read-only"
      },
      {
        "type": "boolean",
        "field": "powered",
        "mutability": "read-write"
      },
      {
        "type": "percentage",
        "field": "brightness",
        "mutability": "read-write"
      },
      {
        "type": "string",
        "field": "color_model",
        "choices": [
          "rgb",
          "hsb",
          "color_temperature"
        ]
      },
      {
        "type": "percentage",
        "field": "hue",
        "mutability": "read-write"
      },
      {
        "type": "percentage",
        "field": "saturation",
        "mutability": "read-write"
      },
      {
        "type": "integer",
        "field": "color_temperature",
        "range": [
          2000,
          6500
        ],
        "mutability": "read-write"
      }
    ],
    "color_changeable": true
  },
  "triggers": [],
  "manufacturer_device_model": "sylvania_sylvania_rgbw",
  "manufacturer_device_id": null,
  "device_manufacturer": "sylvania",
  "model_name": "Lightify RGBW Bulb",
  "upc_id": "593",
  "upc_code": "046135737039",
  "gang_id": null,
  "hub_id": "284481",
  "local_id": "37",
  "radio_type": "zigbee",
  "linked_service_id": null,
  "lat_lng": [
  ],
  "location": "",
  "order": 0
},
```

Full color:

```
{
      "uuid": "6b638758-02f8-4288-9e03-011143029c0b",
      "desired_state": {
        "powered": true,
        "brightness": 1,
        "color_model": "hsb",
        "hue": 0.98,
        "saturation": 1,
        "color_temperature": 2000
      },
      "last_reading": {
        "connection": true,
        "connection_updated_at": 1472687810.529564,
        "powered": true,
        "powered_updated_at": 1472687810.529564,
        "brightness": 1,
        "brightness_updated_at": 1472687810.529564,
        "color_model": "hsb",
        "color_model_updated_at": 1472687810.529564,
        "hue": 0.98,
        "hue_updated_at": 1472687810.529564,
        "saturation": 1,
        "saturation_updated_at": 1472687810.529564,
        "color_temperature": 2000,
        "color_temperature_updated_at": 1472687810.529564,
        "firmware_version": "0.1b02 / 0.3b32",
        "firmware_version_updated_at": 1472687810.529564,
        "firmware_date_code": "20151210N****",
        "firmware_date_code_updated_at": 1472687810.529564,
        "desired_powered_updated_at": 1472687808.5453935,
        "desired_brightness_updated_at": 1472687963.192082,
        "desired_color_model_updated_at": 1472687963.192082,
        "desired_hue_updated_at": 1472687808.5453935,
        "desired_saturation_updated_at": 1472687808.5453935,
        "desired_color_temperature_updated_at": 1472687963.192082,
        "desired_powered_changed_at": 1472687808.5453935,
        "desired_brightness_changed_at": 1472687562.3574722,
        "desired_color_model_changed_at": 1472607043.4553785,
        "desired_color_temperature_changed_at": 1472607043.4553785,
        "powered_changed_at": 1472687562.2804945,
        "desired_hue_changed_at": 1472687808.5453935,
        "desired_saturation_changed_at": 1472687808.5453935,
        "color_model_changed_at": 1472687808.3430905,
        "hue_changed_at": 1472687808.3430905,
        "saturation_changed_at": 1472687808.3430905
      },
      "subscription": {
        "pubnub": {
          "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
          "channel": "b6b6473a4da5a341e7b6d31b7f51d6881bc9860b|light_bulb-1477987|user-362284"
        }
      },
      "light_bulb_id": "1477987",
      "name": "Brett's Lamp",
      "locale": "en_us",
      "units": {},
      "created_at": 1456531676,
      "hidden_at": null,
      "capabilities": {
        "fields": [
          {
            "type": "boolean",
            "field": "connection",
            "mutability": "read-only"
          },
          {
            "type": "boolean",
            "field": "powered",
            "mutability": "read-write"
          },
          {
            "type": "percentage",
            "field": "brightness",
            "mutability": "read-write"
          },
          {
            "type": "string",
            "field": "color_model",
            "choices": [
              "rgb",
              "hsb",
              "color_temperature"
            ]
          },
          {
            "type": "percentage",
            "field": "hue",
            "mutability": "read-write"
          },
          {
            "type": "percentage",
            "field": "saturation",
            "mutability": "read-write"
          },
          {
            "type": "integer",
            "field": "color_temperature",
            "range": [
              2000,
              6500
            ],
            "mutability": "read-write"
          }
        ],
        "color_changeable": true
      },
      "triggers": [],
      "manufacturer_device_model": "sylvania_sylvania_rgbw",
      "manufacturer_device_id": null,
      "device_manufacturer": "sylvania",
      "model_name": "Lightify RGBW Bulb",
      "upc_id": "509",
      "upc_code": "4613573703",
      "gang_id": null,
      "hub_id": "284481",
      "local_id": "32",
      "radio_type": "zigbee",
      "linked_service_id": null,
      "lat_lng": [],
      "location": ",
      "order": 0
    },
```

**Comment by TDWhbp** [comment]
I will check when I get home from work.

**Comment by TDWhbp** [comment]
I can only see tuneable white. It has been this way for aslong as I have
had the bulb

**Comment by w1ll1am23** [comment]
So I think I figured it out. Home-Assistant doesn't support hsb color it
currently only has support for RGB and XY.

I find it interesting that the osram bulb response indicates in its choices
array that it supports rgb and hsb, but I see no mention of rgb in the last
reading. Maybe a wink bug?

Anyway, some pretty decent amount of work is going to be needed in Home
Assistant to get hsb support added. I will see what I can do, but without a
bulb to test with it might take some time.

**Comment by TDWhbp** [comment]
would giving you access to mine help?

**Comment by w1ll1am23** [comment]
@TDWhbp Thanks for the offer, that would help but I'll just use this as an excuse to go buy one lol. Not sure how much effort I will be able to put into this over the next few weeks but maybe I'll get lucky and it will be easier than it looks. I'll keep this issue updated with my findings.

**Comment by w1ll1am23** [comment]
https://github.com/home-assistant/home-assistant/pull/3218 fixes this problem.

**Comment by w1ll1am23** [comment]
@bradsk88 We are going to need a change to python-wink for this. The set_state method is making a call to supports_rgb() which is returning true. It then calls the _get_color_as_rgb() which has a bug `return tuple(h, s, v)`, tuple only accepts one value. If this bug is fixed, then the Osram bulb will then hit the rgb code in set_state. I am recommending we comment out the RGB code in set_state for now since I don't believe it is even support by any bulbs. Thoughts?

**Comment by bradsk88** [comment]
@w1ll1am23 That's right.  [That line](https://github.com/python-wink/python-wink/blob/7a2f0ddb594ae15b95c82a8857aa68591b041003/src/pywink/devices/standard/bulb.py#L101) was written because I knew that Wink supported RGB bulbs but I didn't have any, myself, to test with.

**Comment by w1ll1am23** [comment]
So are you okay with commenting that out for now? Or is there another way we should go about this?

**Comment by bradsk88** [comment]
@w1ll1am23 I think you could get away with just changing 

```
return tuple(h, s, v)
```

to 

```
return (h, s, v)
```

**Comment by bradsk88** [comment]
if that doesn't work.  You could change `supports_rgb` to always return false and leave a TODO

**Comment by w1ll1am23** [comment]
Going to have to return false on the supports_rgb, if we just change the return on the _get_color_as_rgb then this will get called.

``` python
            if rgb:
                return {
                    "color_model": "rgb",
                    "color_r": rgb[0],
                    "color_g": rgb[1],
                    "color_b": rgb[2]
                }
```

Which will fail on setting the bulb color.

**Comment by w1ll1am23** [comment]
@bradsk88, this can be closed.
